name: test-app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install docker container
        run: docker-compose up -d
      - name: stop container
        run: docker-compose down
      - name: Install dependencies
        run: yarn
      - name: Dot Env CLI
        run: yarn global add dotenv-cli
      - name: Test
        run: yarn test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
      - name: Push
        run: git push
