name: ACC_FUEL_APP_CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Dot Env CLI
        run: yarn global add dotenv-cli
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
      - name: Test
        run: yarn test
      - name: Push
        run: git push
